[project]
name = "webmap"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14.6"
dependencies = [
    "asyncpg>=0.31.0",
    "fastapi>=0.141.1",
    "geoalchemy2>=0.20.0",
    "geopandas>=1.1.4",
    "psycopg2-binary>=2.9.12",
    "sqlalchemy>=2.0.51",
    "uvicorn>=0.52.1",
]
